### ISSUE TITLE
关于您储存库涉及中信期货的问题沟通

### ISSUE THREAD

**Issue by yeeton-bj** [sorahjy/fund-excess-returns-checker#4]
您好，
我们是中信期货股份有限公司提供安全服务的厂商-北京亿盾互联科技有限公司。受中信期货委托，跟您沟通有关中信期货问题。经银行技术部门反馈，您在github上发布的以下1个链接中的内容涉及中信期货的关键字数据，现在中信期货进行护网行动需要删除银行关键信息。请麻烦您删除下此链接相关内容，谢谢配合！

 内容链接：
https://github.com/sorahjy/fund-excess-returns-checker/blob/c7bd1026eba76a2bf740ac81dbf3be2792c83f19/citic_futures.py

**Comment by sorahjy** [comment]
done
